name: Build and push Docker images
on:
  push:
    branches:
      - 'main'
      - '!testing/**'
      - '!feature/**'
      - '!hotfix/**'

jobs:
  build-and-push-image:
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        version: [1.82.0, 1.81.0, 1.80.0, 1.79.0, 1.78.0, 1.77.0, 1.76.0, 1.75.0, 1.74.0, 1.73.0, 1.72.0, 1.71.0, 1.70.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: maxkratz/boost:${{ matrix.version }}
          platforms: linux/amd64
          build-args: |
            boost_version=${{ matrix.version }}

  # latest is an extra build step because of buggy GitHub Actions if conditions
  build-and-push-latest-image:
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        version: [1.83.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build latest image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            maxkratz/boost:${{ matrix.version }}
            maxkratz/boost:latest
          platforms: linux/amd64
          build-args: |
            boost_version=${{ matrix.version }}
